name: Deploy to remote server
description: Deploy to remote server

inputs:
  deploy_ssh_private_key:
    description: SSH private key
    required: true
  deploy_ssh_host:
    description: SSH host
    required: true
  deploy_ssh_port:
    description: SSH port
    required: true
  deploy_ssh_user:
    description: SSH user
    required: true
  deploy_instance:
    description: Deploy instance
    required: true
  deploy_type:
    description: Deploy type
    required: false
    default: ""
  deploy_build_cmd:
    description: Build command
    required: false
    default: ""
  deploy_exec_start:
    description: Start command
    required: false
    default: ""
  deploy_db:
    description: Database name
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.deploy_ssh_private_key }}

    - name: Add remote host to known_hosts
      shell: bash
      run: |
        ssh-keyscan -p ${{ inputs.deploy_ssh_port }} ${{ inputs.deploy_ssh_host }} >> ~/.ssh/known_hosts

    - name: Generate deploy.yml
      shell: bash
      run: |
        cat > deploy.yml <<EOF
        ${{ inputs.deploy_instance }}:
          ssh_host: ${{ inputs.deploy_ssh_user }}@${{ inputs.deploy_ssh_host }}
          ssh_port: ${{ inputs.deploy_ssh_port }}
          repo_url: git@github.com:${{ github.repository }}.git
        EOF

    - name: Have type of deploy if specified
      if: ${{ inputs.deploy_type != '' }}
      shell: bash
      run: |
        echo "  type: ${{ inputs.deploy_type }}" >> deploy.yml

    - name: Append build_cmd to deploy.yml if exist
      if: ${{ inputs.deploy_build_cmd != '' }}
      shell: bash
      run: |
        echo "  build_cmd: ${{ inputs.deploy_build_cmd }}" >> deploy.yml

    - name: Append exec_start to deploy.yml if exist
      if: ${{ inputs.deploy_exec_start != '' }}
      shell: bash
      run: |
        echo "  exec_start: ${{ inputs.deploy_exec_start }}" >> deploy.yml

    - name: Append db to deploy.yml if exist
      if: ${{ inputs.deploy_db != '' }}
      shell: bash
      run: |
        echo "  db: ${{ inputs.deploy_db }}" >> deploy.yml

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install deploy
      shell: bash
      run: uv tool install "git+https://github.com/trobz/deploy.py.git"

    - name: Deploy
      shell: bash
      run: |
        deploy --config deploy.yml --verbose update ${{ inputs.deploy_instance }}

branding:
  icon: "box"
  color: "orange"
